### ISSUE TITLE
How to update `data/fills.txt`

### ISSUE THREAD

**Issue by francescobrivio** [MilanoBicocca-pix/BeamspotTools#4]
Since the end of Run2 the WBM page used to collect and download the info on the fills does not work anymore and has been replaced by OMS.

So we need to find a new way to populate `data/fills.txt`. There are different options
1. switch completely to OMS
    - this will require writing new `utils/fillRunDict.py` and `objets/Fill.py` classes
    - understand how to get from OMS the needed info (it's possible to download csv frmo OMS website but it does not have the same info that were in WBM)
 2. Find a way to still get data from WBM (honestly I don't think it's been updated anymore so option 1 seems the only way...)
 3. Populate "by hand" the `data/fills.txt` file. Seems un.maintainable in the future and very error-prone.

**Comment by gennai** [comment]
The only possible option is the first one. OMS has a number of API calls to access information we may need from python scripts. We should check what is available in their git repository
